spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  application:
    name: IoTMining - Tenant Management service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}