spring:
  flyway:
    locations: classpath:db/migration
    keyspace: iotmining
    enabled: true
    driver-class-name: org.flywaydb.database.cassandra.CassandraDriver
    baseline-on-migrate: true
    url: jdbc:cassandra://localhost:9042/iotmining
    user: cassandra # If your Cassandra has authentication
    password: cassandra # If your Cassandra has authentication

  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    keyspace-name: iotmining
    schema-action: none # CREATE_IF_NOT_EXISTS
#    username: cassandra
#    password: cassandra
    local-datacenter: datacenter1

services:
  dms:
    url: http://localhost:8084 # URL where DMS is running
server:
  port: 8083



flyway:
  locations: classpath:db/migration
  keyspace: iotmining
  enabled: true
  driver-class-name: org.flywaydb.database.cassandra.CassandraDriver
  baseline-on-migrate: true
  url: jdbc:cassandra://localhost:9042/iotmining
  user: cassandra # If your Cassandra has authentication
  password: cassandra # If your Cassandra has authentication