spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  application:
    name: IoTMining-Tenant-Management-Service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8061

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true  # Use IP instead of hostname for discovery
