name: PR Checks

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read    # to read parent from GH Packages for mvn
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      # settings.xml so mvn can resolve the parent from GH Packages
      - name: Write settings.xml with GH Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${env.ACTOR}</username>
                <password>${env.TOKEN}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github-repo</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/${env.REPO_OWNER}/platform-build</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github-repo</activeProfile>
            </activeProfiles>
          </settings>
          XML
        env:
          ACTOR: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}

      - name: Build & Test
        run: mvn -B -s ~/.m2/settings.xml -Pci clean verify
