name: CI/CD • TMS

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/release-tms.yml'
  pull_request:
    paths:
      - '**'
      - '.github/workflows/release-tms.yml'
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/iotmining/tenant-management-service
  JAVA_VERSION: '21'

concurrency:
  group: tms-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Prepare GitHub Packages settings.xml
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SETTINGS="$RUNNER_TEMP/gpr-settings.xml"
          TOKEN="${GH_PACKAGES_TOKEN:-$GITHUB_TOKEN}"
          cat > "$SETTINGS" <<XML
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GH_USERNAME}</username>
                <password>${TOKEN}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github-packages</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/iotmining/platform-build</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github-packages</activeProfile>
            </activeProfiles>
          </settings>
          XML
          echo "GPR_SETTINGS=$SETTINGS" >> "$GITHUB_ENV"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=sha-${{ github.sha }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry (GHCR)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.workflow
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            gpr=${{ env.GPR_SETTINGS }}
          build-args: |
            SKIP_TESTS=true
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ github.run_id }}
          cache-from: type=gha,scope=tms
          cache-to: type=gha,mode=max,scope=tms
