name: tms-pr
on:
  pull_request:
    branches: [ "**" ]
    paths:
      - "**"
      - ".github/workflows/**"

jobs:
  pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # adjust if POM is not at root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree (debug)
        run: ls -la && echo && find . -maxdepth 2 -name pom.xml -print

      - name: Setup Java 21 + Maven settings for GitHub Packages
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          server-id: github
          server-username: ${{ secrets.GH_PACKAGES_USER }}
          server-password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build & Test
        run: mvn -B -ntp clean verify

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
