name: tms-pr
on:
  pull_request:
    paths: ["services/tms-service/**", ".github/workflows/**"]

jobs:
  pr:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: services/tms-service } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Build & Test
        run: mvn -B -ntp clean verify
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
      - name: Dependency Audit (optional)
        run: mvn -B -ntp org.owasp:dependency-check-maven:check
